# fly.toml app configuration file generated for app-dt-26-6-1-1719378362-client on 2024-06-26T05:06:44Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'app-dt-26-6-1-1719378362-client'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
